version: '3'             #フォーマットのバージョン。現在は3が最新。
services:                #アプリケーションを動かせるための記述
  web:                   #コンテナ名
    image: nginx:latest  #イメージ名
    ports:               #使用ポート
      - "80:80"
    depends_on:
      - app
    volumes: #以下を追記　[ホストのファイルパス]:[コンテナファイルパス]
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      #varはvariable頻繁に変化するファイルに用いられる
  app:
    # image: php:7.2.15-fpm
    image: php:7.4-fpm
    depends_on:
      - db
    volumes:
        - ./src:/var/www/html
    # network_mode: "docker_network"

  db:
    # container_name: mysql1
    # build:
    #   context: ./mysql
    #   dockerfile: Dockerfile
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=questions
      - MYSQL_USER=mayuna_user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
    volumes:
      # MySQLの設定ファイル
      - ./mysql/mysql_conf:/etc/mysql/conf.d
      # - ./mysql/sql:/var/lib/mysql
    # network_mode: "docker_network"

# networks:
#   docker_network:
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1 #自動で入れる設定
      - PMA_HOSTS=db
      - PMA_USER=mayuna_user
      - PMA_PASSWORD=pass
    ports:
      - 8080:80
